#
# This file will be autogenerated by Chef. The node IPs are different
# in each environment (dev, ci, master, staging, prod). In development,
# use the environment variable RIAK_NODES to override. 
# 
# DO NOT MAKE ANY CHANGES TO THIS FILE.
#

# The following gives you the Riak nodes in the Master environment
# NB: Hardcoding the Riak node IPs in this way is not ideal.
RIAK_NODES = ENV['RIAK_NODES'] || ['10.254.1.23', '10.254.1.31', '10.254.1.236']

# The following is the public Riak hostname to use for HTTP GETs
RIAK_MEDIA_URL = OCEAN_API_URL.sub("api.", "media.").sub("forbidden.", "master-media.")
